name: csv file validator

on:
    push:
        branches:
            - main

jobs:
    validate-file:
        runs-on: ubuntu-latest
    
        steps:
            - name: checkout code / download code
              uses: actions/checkout@v7
            
            - name: run read program
              env:
                USERNAME_ENV: ${{secrets.USERNAME}}
                PASSWORD_ENV: ${{secrets.PASSWORD}}
              run: python read.py
